### ISSUE TITLE
Question: why is tkinter module not supported?

### ISSUE THREAD

**Issue by AngryMax** [Felk/dolphin#16]
When running a script with tkinter imported, this exception is thrown: `Script stderr: ModuleNotFoundError: No module named 'tkinter'`

After doing some research, I see that [ext-python](https://github.com/Felk/ext-python/blob/2c19586a003ba5616d6b0ad189ec93876708f34e/README.md) specifically says to not copy over tkinter for the embed. So before trying to make a build that includes tkinter myself, I figure I could perhaps save some time and ask: for what reason is tkinter not included with the embed? Does it break Python Dolphin? Or am I safe to make a build with it included? Or alternatively, am I just overlooking something obvious?

For context, I've been co-developing an online mod for Super Mario Sunshine, and we use Python Dolphin for communicating between games. I'm trying to (easily) make a pop-up GUI to change settings on the fly and run commands.

Thank you, and I hope you're having a great day/night :^)

**Comment by Felk** [comment]
Hey there,

you should be able to make a build with tkinter included (or just adding the missing dll might be enough). The only reason I removed it is because I didn't think anyone would need it and it takes up a bunch of space. I'm not aware of any reason why it wouldn't work, but I haven't tested it

**Comment by AngryMax** [comment]
Thanks for the response, very much appreciated!
