### ISSUE TITLE
Copyright status of user python scripts.

### ISSUE THREAD

**Issue by luckytyphlosion** [Felk/dolphin#36]
Python scripts would import the dolphin library, which is under GPL. Does this mean that anyone who makes a script for Dolphin has to release the script under a GPL compatible license? According to the [FSF faq](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL), if the library is GPL, then any program that, but I presume this has to do with libraries which are compiled into the program, and I'm not sure how this applies for a python source file.

**Comment by Felk** [comment]
> Does this mean that anyone who makes a script for Dolphin has to release the script under a GPL compatible license?

I'm not a lawyer and this is not legal advice, but I think the answer is "no". The script itself is probably not constrained by the GPL. Only if you would distribute it together with a copy of Dolphin would the GPL apply to the whole. Since a Python script only interfaces with Dolphin through an API, scripts can be considered their own thing, similarly to how a proprietary piece of software is allowed to talk to a GPL-licensed service via HTTP.
